### ISSUE TITLE
6 digit TID

### ISSUE THREAD

**Issue by fuhckos-98** [Admiral-Fish/RaidFinder#1]
I found that when entering my TID mine was 6 digits and the maximum was 5

**Comment by Admiral-Fish** [comment]
I assume you are using PKHeX to view TID/SID. Hover over the TID/SID field where it will show the 5 digit ID and TSV.

**Comment by fuhckos-98** [comment]
Oh my bad! Thank you for the response :)

**Comment by Th3Alic3** [comment]
There are three numbers that pop-up.
TSV: no1
ID: no2 / no3

Is it the second 5 digit number or the third 5 digit number?

**Comment by Admiral-Fish** [comment]
ID lists TID/SID
