### ISSUE TITLE
Shiny Type Calculation Problem

### ISSUE THREAD

**Issue by dewblackio2** [Admiral-Fish/RaidFinder#12]
I've been in the process of calculation den seeds, and noticed that after targeting Den #49 (in tool) #82 (on serebii), the seed that was retrieved had shiny results appear correctly in version 1.3.2.

However after updating to 1.3.3 the seed was input again, and there were no shiny results at all.

**The seed in question**: 0xCFA738978AFDFB33

Here are some images taken from the listed versions containing the information as well as inputs to show it is not user error:

**Version 1.3.2:**
![Version 1.3.2](https://i.gyazo.com/ea9b493cef44b554f056be1e270b1b0d.png)

**Version 1.3.3:**
![Version 1.3.3](https://i.gyazo.com/21dc89a20c99197a5692bc433bb4fe7b.png)

The inputs didn't change, they were exactly the same. I do believe either the Den contents were updated in recent commits and weren't noted, or the shiny type calculation broke with recent changes.

**Comment by Admiral-Fish** [comment]
I released a hot fix for 1.3.3 to fix an issue with shiny type calculation.

Can you redownload and test again to make sure you have the hotfix edition?

**Comment by dewblackio2** [comment]
> I released a hot fix for 1.3.3 to fix an issue with shiny type calculation.
> 
> Can you redownload and test again to make sure you have the hotfix edition?

Do you have a link for the hotfix edition? I just pull from your releases on github, and I do not see an installer/zip for x64 windows labeled "hotfix"

Edit: my apologies its in the sub description of the 1.3.3 release. I will re-download and test again.

**Comment by Admiral-Fish** [comment]
I just redid the release. The notes contain hotfix at the top.

If you just redownload 1.3.3 it will contain the hotfix.

**Comment by dewblackio2** [comment]
That hotfix seems to have fixed the issue.

![Version 1.3.3](https://i.gyazo.com/d904fcc3bc8d57c04b09036fff0d365d.png)

**Comment by dewblackio2** [comment]
Thank you for the prompt response, and quick fix to the issue!
