### ISSUE TITLE
problem with den: 49 

### ISSUE THREAD

**Issue by ard0s** [Admiral-Fish/RaidFinder#14]
in the den 49 in bridge field it doesnt show rapidash as an option

**Comment by Admiral-Fish** [comment]
Is it supposed to?

**Comment by dewblackio2** [comment]
Do you have your game set to Shield in your profile?

Edit: I just checked on the latest version, rapidash is appearing in Den 49 correctly, for both normal and rare beams.

**Comment by Admiral-Fish** [comment]
Yes as @dewblackio2 mentioned select a profile with Shield.
