### ISSUE TITLE
User Profile - Trainer ID

### ISSUE THREAD

**Issue by Th3Alic3** [Admiral-Fish/RaidFinder#18]
![image](https://user-images.githubusercontent.com/57371173/72214710-46877580-34bc-11ea-9936-5119476f6c6a.png)

![image](https://user-images.githubusercontent.com/57371173/72214731-8ea69800-34bc-11ea-9e80-1de01ae96897.png)

The Profile won't let me enter all 6 digits for the Trainer ID. (Is it because I started a new save in v1.1.0?)

**Comment by Admiral-Fish** [comment]
#1
