### ISSUE TITLE
Seed Calculator doesn't return any result

### ISSUE THREAD

**Issue by remokon** [Admiral-Fish/RaidFinder#19]
Hi Admiral Fish, 
me and @armisael have tested the newly added Seed Calculator with information we already know produced a seed according to 1sss by rusted-coil.
However when having it run on Raid Finder's Seed Calculator no result is returned. The seed is supposed to appear in the "Search Results", correct?

Thank you for your time, and thanks once again for the great work.

**Comment by Admiral-Fish** [comment]
Without knowing the search settings I can't do anything

**Comment by armisael** [comment]
Den: 28 (Axew's Eye)
Rarity: Common
Game: Sword
Use day 6: yes
Day 4: 18 / 2 / 31 / 31 / 20 / 31, Drakloak, Relaxed, Infiltrator, Mischievous
Day 4: 5 / 11 / 31 / 31 / 31 / 31, Noivern, Bold, Infiltrator, Mischievous
Day 5: 31 / 31 / 8 / 31 / 31 / 23, Noivern, Gentle, Frisk, Somewhat vain
Day 6: 26 / 31 / 31 / 3 / 31 / 31, Hakamo-o, Quiet, Soundproof, Likes to trash about
Expected seed: 0x15f4403072e70423

**Comment by Admiral-Fish** [comment]
Do you happen to know the IV deviation that found this spread?

**Comment by armisael** [comment]
Unfortunately I don't, I'm sorry

**Comment by armisael** [comment]
How can I find out the IV deviation? Would adding a `System.out.println` somewhere in xoroshiro-inverse do? Let me know if I can help in some way.

**Comment by Admiral-Fish** [comment]
IV deviation is 3. For reference the seed is actually 0x8E0C2BD10B0EC512. It would be helpful to post the seed from the actual day 1 instead of day 4 to cause me less confusion.

Appears to have been fixed by 6564dd7

![image](https://user-images.githubusercontent.com/24730718/73117266-f8349680-3eff-11ea-874e-1df32c1a4d9b.png)

**Comment by armisael** [comment]
Ah, sorry for that, I just wrote you what xoroshiro-inverse printed me, I didn't realize you needed the day 1.

Glad to hear you fixed the issue, we'll give it a shot on some other combinations, it's so nice to have everything in one, powerful tool.

Thank you for your excellent work!
