### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by devg87** [Admiral-Fish/RaidFinder#2]
Getting the following error when trying to run raid_solver:

**File "/Users/Home/Downloads/RaidFinder-1.0.0/raid_solver.py", line 123
    print(f"Raid seed: {hex(seed)}")
                                  ^
SyntaxError: invalid syntax**

Any help appreciated.

**Comment by Admiral-Fish** [comment]
Run with python 3.7

**Comment by devg87** [comment]
That worked. Thanks for the help!
