### ISSUE TITLE
drop down UIs are broken on macOS Mojave (QDarkStyle)

### ISSUE THREAD

**Issue by matxx** [Admiral-Fish/RaidFinder#23]
all drop downs have huge empty spaces on macOS Mojave

screenshots are from 1.3.3 but the problem still exists on 2.0.0

![image](https://user-images.githubusercontent.com/990728/72384989-d3316e00-371e-11ea-9078-724aca22213a.png)

![image](https://user-images.githubusercontent.com/990728/72385075-01af4900-371f-11ea-84c4-f8326a54a5b2.png)

![image](https://user-images.githubusercontent.com/990728/72385087-070c9380-371f-11ea-80c1-c7eec617ea7c.png)

edit : they are still functionnal (to select things), just some weird spaces

**Comment by Admiral-Fish** [comment]
What if you change the style to light?

**Comment by armisael** [comment]
Switching to light style fixes the issue, so I guess this should be notified to https://github.com/ColinDuquesnoy/QDarkStyleSheet/ ?

**Comment by daphnegold** [comment]
Came here to also create an issue about this. Interesting that changing the style to light fixes it. Thanks so much for your quick response @Admiral-Fish !

**Comment by matxx** [comment]
yeah, light style fixes the issue haha

**Comment by Admiral-Fish** [comment]
Any UI issues that I don't experience myself I can usually blame on the stylesheet. There is already an open issue on their repo for it.

https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/200

**Comment by johnmquick** [comment]
I also experienced this problem with the drop-down menus on Mac OS 10.15.3. By chance, I changed from dark mode to light mode and the drop-down menus now appear to be displaying properly. I don't know if it is related to which mode is selected or the fact that I changed modes.

**Comment by johnmquick** [comment]
Update: This only appears when selecting the dark theme.

**Comment by Abu-ZaydAbdullah** [comment]
There is actually an aesthetic fix for this if you are willing to build from source. Simply add `height: 18px;` to the `QComboBox::item:checked` class in QDarkStyleSheet/qdarkstyle/style.qss which at the time of writing starts at line 1263.

**Comment by Admiral-Fish** [comment]
Fixed by fa3fafa
