### ISSUE TITLE
[Seed Checker not working properly]

### ISSUE THREAD

**Issue by jdmentolaroc** [Admiral-Fish/RaidFinder#25]
Hi, the current seed checker when opened has a default value of INVALID. when tried adding a valid IV from the IV calculator it always display invalid on the 1st 4th frame on 1st column.

**Comment by remokon** [comment]
Hey, I actually tried various combinations I know are valid for 1sss and I get the correct result also in Raid Finder. What is your combination that gets you invalid?

Can you try this one too and see if it returns valid? 
Den 59 (rare) - Ditto 2/3*
19 31 31 31 31 7 28
Careful / Limber / Likes to thrash about

**Comment by jdmentolaroc** [comment]
Hey. I just tried it and I got it worked. Maybe there are apecifics pokemon
or instances that it will not work? In my case, I tried it twice and both
failed. Here is one of the info i got from my trial yesterday.

Maybe it differs from den or pokemon?

This is for Den 98. Rare beam

**Comment by remokon** [comment]
Cannot see anything after your:
> This is for Den 98. Rare beam

Also, how did you check the settings were valid? 1sss https://rusted-coil.hateblo.jp/1sss_down? raid iv validator https://github.com/Elveman/Raid-IV-Validator?

**Comment by jdmentolaroc** [comment]
This is one of the info I have

Charmeleon

2 IV
Serious nature
Blaze
Alert to sounds

Stat distirbution
10 31 14 31 10 31 (Lvl 100)

Meaning not all pokemon are valid for seed checking? I have to do some seed
checker first before I plug in a pokemon on first 4th frame? Btw, I can't
access the 2 links. It's not opening on my end..

**Comment by remokon** [comment]
Ah well that's very easily solved, your Charmeleon has a random third 31IV — when it's supposed to be 2IV guaranteed only — so it will never be valid. This is because the seed calculator cannot know which one of these three is the random 31.

Moreover, even when there is no third random 31IV, not all 2IV are valid as the seed search cannot always determine a seed. In case of 3IV guaranteed I was told it's a 15% chance of having a valid IV combination, but I've found that the "valid" chance is higher for 2IV (no official data or source to support this sorry).

Anyway, whenever you find a 4th frame (aka Day 4) to be invalid, simply do a hard single advancement, save, and catch another 2IV on the new Day 4 — former Day 5 — then check its IVs. Repeat this until your 2IV on Day 4 is valid.

**Comment by jdmentolaroc** [comment]
Hi,

Thank you for the detailed explanation. So basically, if I encounter a
frame that has 3IV instead of 2IV, I will move 1 day forward, save it then
catch the frame to check if it's 2IV. Repeat until I get a 2IV. How will I
determine if the 2 IV is valid? Since you mention that not all 2 IVs are
valid, is there an application that we can use to validate the first 4th
frame 2IV? Also, another clarification, if my current date stamp is January
01, 2000 and I throw a piece, then I do a checking on 4th, invalid, moved 1
day valid. Technically, that is 5 frames already, correct? So when I got
the seed (assumed) and run the raid finder, I will start my counting from
January 01,2000 1st frame?

Thanks

**Comment by remokon** [comment]
Yes, when you finally find your 2IV guaranteed pkmn on your Day 4 — in your case it can only be a 3* Charmeleon or 3* Heatmor — and it has an extra third 31 IV,  you need to do one permanent advancement and try again.
The way you check if that pkmn is valid is exactly the tool's purpose for that Day 4 output: if it's invalid, you need to do that hard single advancement. If it's ok it will prompt something like: "OK → 3IV" which means you'll have the catch a 3IV guaranteed on Day 4 next.

> Also, another clarification, if my current date stamp is January
> 01, 2000 and I throw a piece, then I do a checking on 4th, invalid, moved 1
> day valid. Technically, that is 5 frames already, correct?

No. Let's say you have these as your first 3 frames (always predetermined): Salazzle 4*, Arcanine 5* and Heatmor 3*. You get a Charmeleon with 2IV that is invalid in that Day 4. You reset, advance from Salazzle to Arcanine and save (without doing the raid of course). 
Then you try again: you'll have Arcanine, Heatmor, another random one and your new Day 4. Reset until you get a Heatmor or Charmeleon etc. etc.

Anyway please watch im a blisy's video as everything there is detailed: https://www.youtube.com/watch?v=XViOuNwIf1I

**Comment by jdmentolaroc** [comment]
> No. Let's say you have these as your first 3 frames (always predetermined): Salazzle 4*, Arcanine 5* and Heatmor 3*. You get a Charmeleon with 2IV that is invalid in that Day 4. You reset, advance from Salazzle to Arcanine and save (without doing the raid of course).
> Then you try again: you'll have Arcanine, Heatmor, another random one and your new Day 4. Reset until you get a Heatmor or Charmeleon etc. etc.

Thank you for the explanation again.  I don't really get it 100% but this will be my asumption while I am watching the video, if i got invalid on my 4th frame. I reset advance to arcanine, save. Then I get my valid IV i did seed checking, then on raid finder it says that my shiny is on 11th frame, meaning since I moved 1 forward from salazlle it will be 11-1 since i skipped salazzle? Hope that is correct for the frame counting.  Anyway, thanks for the great explanation. i will sure to re watch the tutorial and keep trying. Thank you.
