### ISSUE TITLE
option to select sword/shield

### ISSUE THREAD

**Issue by matxx** [Admiral-Fish/RaidFinder#28]
I was hunting for shiny gengar and could not find the correct den ID because the list of pokemons in dens are for the sword version (and I'm on shield).

Ex : in the den 60, raid finder says there's machamp, but in fact, in shield, it's gengar.

it did not affect the number of frames to skip to shiny fortunately.

**Comment by Admiral-Fish** [comment]
Make a profile with the game you want selected
