### ISSUE TITLE
[Suggestion] Add Height / Weight Values

### ISSUE THREAD

**Issue by crzyc** [Admiral-Fish/RaidFinder#33]
Source code made by Archit: https://github.com/architdate/PKHeX-Plugins/blob/master/PKHeX.Core.AutoMod/AutoMod/APILegality.cs

I think this is enough information for implementation?

**Comment by Admiral-Fish** [comment]
These are purely cosmetic values. What would be the purpose of displaying them?

**Comment by crzyc** [comment]
No _good_ reason, but I do want to be able to see an XL Diggersby. You can close this if you'd like.
