### ISSUE TITLE
Cannot Add TID

### ISSUE THREAD

**Issue by Abu-ZaydAbdullah** [Admiral-Fish/RaidFinder#36]
The Text Input inside the profile manager does not allow you to add any TIDs that are over 5 digits. I presume this is due to the TID being stored in a u16 which caps at 65,535.

**Comment by Admiral-Fish** [comment]
That would be the case

**Comment by Abu-ZaydAbdullah** [comment]
Sorry just noticed the issue was already closed by #1 .
