### ISSUE TITLE
"Search settings are invalid" in Seed Calculator

### ISSUE THREAD

**Issue by PewnyPL** [Admiral-Fish/RaidFinder#37]
I'm using the 2.1.0 version. I started a rare den, saved and from there am advancing 3 times to get to 4th frame. I calculated IV's using the built-in calculator (here is a screenshot for an example: [https://i.gyazo.com/e0cce187bf71824797981e6f29ed9f72.png](https://i.gyazo.com/e0cce187bf71824797981e6f29ed9f72.png)), filled out the form, but when I proceed to try and calculate the seed I receive the "Search settings are invalid" error message.

I'm 100% sure that the IVs are correct, in fact I've managed to get the exact same 3 pokemon again after resetting for day 4 and day 5 on another try, with IVs and natures being exactly the same. This is how my search looks like: [https://i.gyazo.com/24ce285fbf506cfeb4554d6c16c983d5.png](https://i.gyazo.com/24ce285fbf506cfeb4554d6c16c983d5.png)

**Comment by Admiral-Fish** [comment]
Some IV spreads won't work for the search. You might need to choose another pokemon or advance a day and try again.

**Comment by PewnyPL** [comment]
Oooooh, alright, that makes sense. Sadly I checked all pokemon from the den that match, no good, advance it is.

If I could suggest something, perhaps alter the string "Invalid" or the one in error window to say something akin to "Try different day 4 (1st) pokemon or advance a day"?
