### ISSUE TITLE
App crashes after seed is apparently not found

### ISSUE THREAD

**Issue by remokon** [Admiral-Fish/RaidFinder#38]
Hey, I was trying out the Seed Search on an Event Den (hence using the 3IV guaranteed as first mon method).
This time around after the estimated 3hrs of time are elapsed the app crashes, possibly as the result of not finding any seed.

Here are my settings:

```
Day 4 (1st) | Lapras | 3* | 5 | 31 | 1 | 10 | 31 | 31 | Lax | Shell Armor |  Somewhat vain
Day 4 (2nd) | Lapras | 4* | 9 | 31 | 31 | 15 | 31 | 31 | Bold | Shell Armor | Somewhat vain
Day 5 | Lapras | 3* | 31 | 31 | 2 | 12 | 31 | 8 | Quiet | Shell Armor | Takes plenty
Day 6 | Milcery | 3* | 31 | 17 | 31 | 2 | 15 | 31 | Bashful | Sweet Veil | Capable of
```

Raid Finder version is 2.2.0, running on Ubuntu 18.04.

This is all I could find in the logs:

```
Feb  2 22:40:02 $user raidfinder.desktop[29922]: pure virtual method called
Feb  2 22:40:02 $user raidfinder.desktop[29922]: pure virtual method called
Feb  2 22:40:02  $user  raidfinder.desktop[29922]: terminate called recursively
Feb  2 22:40:02  $user  raidfinder.desktop[29922]: terminate called without an active exception

```

**Comment by Abu-ZaydAbdullah** [comment]
I can check your seed if you want having the extra information might be helpful for debugging.

**Comment by Admiral-Fish** [comment]
So the search finished and then the program crashed afterwards?

**Comment by remokon** [comment]
Yes. It seemed to have reached 100% and immediately crashed afterwards.

**Comment by Admiral-Fish** [comment]
Do you happen to know the seed through external means?

**Comment by remokon** [comment]
Unfortunately no.

**Comment by Admiral-Fish** [comment]
Seed is 0xC1CB8AE98D1CA633 with IV deviation of 5
