### ISSUE TITLE
Event den not available for 2.2.0

### ISSUE THREAD

**Issue by bobofung1109** [Admiral-Fish/RaidFinder#42]
I am using 2.2.0 (mac). However, event den is not available under the drop down menu of den in both raid finder and seed calculator.

**Comment by Admiral-Fish** [comment]
You must download the event den of your choice. On the main window Tools -> Download Event Data

**Comment by bobofung1109** [comment]
Thank you for reply. But after I have downloaded the data, I cannot find "event den" under den.
<img width="336" alt="Screenshot 2020-02-07 at 2 45 09 AM" src="https://user-images.githubusercontent.com/60753403/73968002-f0d7a900-4953-11ea-8640-9b0b27e79747.png">

**Comment by Admiral-Fish** [comment]
Are you running RaidFinder from the .dmg or a .app file?

**Comment by bobofung1109** [comment]
dmg file

**Comment by Admiral-Fish** [comment]
Extract out the .app from the .dmg and try again

**Comment by bobofung1109** [comment]
oh! got it! thanks a lot!
