### ISSUE TITLE
App crashes after selecting event den

### ISSUE THREAD

**Issue by MrPanda77** [Admiral-Fish/RaidFinder#43]
After getting the toxtricity den update, When i try to select event den option the apps crashes

**Comment by Radzzzz** [comment]
Same here

**Comment by Admiral-Fish** [comment]
Fixed by 98e0c80

I will pushing 2.2.1 in a few minutes which you will also want to download as I made some internal changes

**Comment by MrPanda77** [comment]
Thank you admiral fish for the quick update!

**Comment by Admiral-Fish** [comment]
https://github.com/Admiral-Fish/RaidFinder/releases/tag/v2.2.1

Let me know if any issues persist
