### ISSUE TITLE
MAC OS no event den

### ISSUE THREAD

**Issue by cbritenstine** [Admiral-Fish/RaidFinder#44]
![Screen Shot 2020-02-08 at 1 41 13 PM](https://user-images.githubusercontent.com/60805297/74079312-c7fd0400-4a78-11ea-9f30-3c15b3b4e161.png)
After downloading the new raidfinder, the event den option has disappeared. I'm working on Mac OS, and it was working before the download.

**Comment by Admiral-Fish** [comment]
Tools -> Download event data

**Comment by cbritenstine** [comment]
I have done that, but the event den doesn't appear.

**Comment by Admiral-Fish** [comment]
Extract the .app from the .dmg file and try again

**Comment by cbritenstine** [comment]
How would I go about that? I'm new to this coding thing.

**Comment by cbritenstine** [comment]
I just figured it out, thank you!
