### ISSUE TITLE
Button to Send IVs to Seed Calculator

### ISSUE THREAD

**Issue by Regiultima** [Admiral-Fish/RaidFinder#47]
This issue was created to be a reminder for the idea of either buttons to send the IVs directly from the IV calculator to the Seed Calculator or a method to copy/paste the IVs to the Seed Calculator mentioned on Discord.  Thank you for all your hard work Fish.

**Comment by Ich73** [comment]
If you add a button IV Calculator to Seed Calculator the nature should be transfered as well.
