### ISSUE TITLE
Raid Finder Crashes When Searching Event Dens

### ISSUE THREAD

**Issue by skwen** [Admiral-Fish/RaidFinder#48]
Ever since the latest event update (adding toxtricity), I've downloaded the event data for that event. However, when trying to switch to event dens, the program (windows, 64 bit version) crashes instead of giving the option to generate frames for that den.

My best guess is the downloaded event data is formatted incorrectly since it was working when using raidfinder with older event dens.

**Comment by Admiral-Fish** [comment]
What version of RaidFinder are you using

**Comment by skwen** [comment]
I'm currently using 2.2.0. If there's a newer version I should try, I'd be happy to and report back.

**Comment by Admiral-Fish** [comment]
https://github.com/Admiral-Fish/RaidFinder/releases/tag/v2.2.1

**Comment by skwen** [comment]
Ah sorry, must have missed that.
