### ISSUE TITLE
Seed Searcher Crashes After Reaching 100%

### ISSUE THREAD

**Issue by johnmquick** [Admiral-Fish/RaidFinder#49]
I've seen this bug reported a few times by others and closed (with the author providing a seed). However, I haven't noticed any updates to the software to prevent future occurrences or address the underlying issues causing these crashes. Therefore, I pulled a few crash logs from Mac OS to hopefully contribute additional information to this topic that can result in more stable future releases.

Attached is a screenshot of Den 78. The monster data is complete and verified as accurate. Also attached are two crash logs (the first occurred without "Stop after first result" ticked and the second occurred with it ticked). 

This is a specific case of a common problem I've had in my time using RaidFinder 2.1, 2.2, and 2.21 on Mac OS. I am 100% certain that acceptable Day 4 (1st) and accurate subsequent catches are being found in my trials, resulting in accurate input data. However, the seed searcher crashes about 90% of the time without reporting a seed. 

The patterns are not entirely clear. Sometimes it runs 30 minutes, sometimes 120. I have had successes and crashes, both quickly and after a long wait. I have tried several dens and even tried multiple acceptable monsters within dens. While I have used the software to successful find the seed of some dens, the most common outcome by far is a crash like this one.

Thanks for your efforts on this project.

<img width="1674" alt="RaidFinder_Den78Rare_SeedSearch" src="https://user-images.githubusercontent.com/6595227/74220424-8b384380-4cea-11ea-8d95-5af609b860ae.png">

[RaidFinder_20200211_CrashLog_01.txt](https://github.com/Admiral-Fish/RaidFinder/files/4184656/RaidFinder_20200211_CrashLog_01.txt)

[RaidFinder_20200211_CrashLog_02_StopAfterFirst.txt](https://github.com/Admiral-Fish/RaidFinder/files/4184657/RaidFinder_20200211_CrashLog_02_StopAfterFirst.txt)

**Comment by johnmquick** [comment]
In case this additional information is helpful for troubleshooting, I was able to pull the seed from RaidFinder 2.1.0 in about 15 minutes with the same data and "Stop after first result" ticked. I also verified the seed with additional catches. The seed is 0xBC3A27A48FE9DF52.

**Comment by Admiral-Fish** [comment]
How many threads are you searching with?

**Comment by johnmquick** [comment]
> How many threads are you searching with?

I see 18 listed in the logs. I just noticed the option for up to 16 in the RaidFinder settings for the first time (with 16 selected as the default). Previously, I never changed/set the number of threads. Is this something I should change?

**Comment by Admiral-Fish** [comment]
There was an issue with having more IV deviation then threads causing a crash but that would be due to a out of bounds error (which is now fixed).

Not sure what exactly to make of these crash logs. It seems to be complaining about calling a pure virtual function which I can only imagine would be searchSeed but that is overridden in the child classes. Unless overriding a protected function in a parent while having it be private in the child is bad.

Also what version of RaidFinder are these crash logs for?

**Comment by johnmquick** [comment]
> Also what version of RaidFinder are these crash logs for?

The logs are from Mac OS 2.2.1.

**Comment by johnmquick** [comment]
Update: Since reducing the threads from 16 (maximum possible) to 14 and running a few tests, I have not had any crashes. Therefore, the previous crash appears to occur at the moment the search ends without finding a result (and some other conditions, possibly related to threads).

However, I also have not found any seeds since the crash disappeared. Thus, I moved over to Boot Camp Windows 10 and the Leanny/SeedSearcher project. Oddly enough, I am able to get a seed out of that program every time within 5-15 minutes. I'm not sure how the programs differ with regards to the search, but the mechanism in RaidFinder does not seem to work well for me on Mac OS. Meanwhile, I am still using RaidFinder for its IV calculator and seed output results, since I prefer the provided format for those features.

**Comment by Admiral-Fish** [comment]
I fixed a searching related issue present in 2.2.1, need to make another update soon

**Comment by Admiral-Fish** [comment]
As of 2.7.0 this feature has been removed in favor of https://github.com/Leanny/SeedSearcher
