### ISSUE TITLE
Can't find correct den?

### ISSUE THREAD

**Issue by koihei** [Admiral-Fish/RaidFinder#5]
I've checked every Dappled Groove den on RaidFinder and none of them match Rare Den 79. Two of the dens with Flapple are close, but the Whimsicott line isn't supposed to be on either off the Flapple dens. Neither of the two Flapple dens are marked GMax as well. 

I am having the same problem with the PK HeX Raid Plugin so I am not sure if I goofed something up, but the list on serebii matches with what I'm getting in-game. Any help would be appreciated. 

Thank you.

Den info on Serebii: https://www.serebii.net/swordshield/maxraidbattles/den79.shtml

![image](https://user-images.githubusercontent.com/25569900/71050302-d10bdc00-217f-11ea-80da-20636a745680.png) ![image](https://user-images.githubusercontent.com/25569900/71050306-d1a47280-217f-11ea-961d-632f5f94a621.png)

![image](https://user-images.githubusercontent.com/25569900/71050252-a9b50f00-217f-11ea-8c30-74ae6c61d813.png)
![image](https://user-images.githubusercontent.com/25569900/71050253-ab7ed280-217f-11ea-8584-e23869bc7795.png)

![image](https://user-images.githubusercontent.com/25569900/71049766-64dca880-217e-11ea-8795-2ddea208541a.png)

**Comment by Admiral-Fish** [comment]
You can see how serebii matches to the actual game from this listing. https://github.com/Admiral-Fish/RaidFinder/blob/master/Core/DenLoader.cpp#L26-L127

What serebii lists as Den 28/79 is actually Den 12.

**Comment by koihei** [comment]
I see it now, thanks!

I will close this now as I've found the den I'm looking for, but I do want to point out that the raid table is still messed up: Den 12 should not have Whimsicott, Ferrothorn is 4-5*, Shiftry should be in there with 3-5*, Flapple should be GMax, etc.

**Comment by Admiral-Fish** [comment]
Data is pulled directly from the game, it is correct.
