### ISSUE TITLE
Download Event Data | Naming Not Intuitive 

### ISSUE THREAD

**Issue by Th3Alic3** [Admiral-Fish/RaidFinder#55]
Hello Fish,

The majority of the people RNG-ing for Pokémon are in the post game. The naming convention of the very first encounter (which is always a One Star Raid) is often a Pokémon no one remembers. _(I was legit scratching my head trying to figure out what event "Krabby" was.)_

![image](https://user-images.githubusercontent.com/57371173/75726845-41fb6400-5c98-11ea-9d95-1a0e22d5c595.png)

It would be fabulous and make the program far more user-friendly if the drop-down names matched the ones used on Serebii.net's:

![image](https://user-images.githubusercontent.com/57371173/75727143-15941780-5c99-11ea-89be-4a535e453dd5.png)

The parallel to Serebii's list would also make it far easier for players are RNG-ing older event downloads.

Thanks

**Comment by Admiral-Fish** [comment]
I don't see how names such as "Pokemon Day" or "February" are anymore descriptive then listing one of the introduced pokemon from the promotion. I am also typically against anything Serebii given the historical inaccuracies I have encountered with the site.

Not to say I'm not open to name changes, but listing a pokemon that the promotion introduced seemed pretty intuitive to me and any changes would likely be incompatible with older versions of the program.

**Comment by Th3Alic3** [comment]
_The topic of accuracy of data on Serebii is not the topic here but still Joe is pretty good at picking naming conventions people remember. Why else do you think the majority of players do not know that the 93 entries on Serebii.net are Nests (not Dens.)_

The internet as a whole refers to Promoted Raids by Date with Year or Event (ie. Christmas) with Year over the Pokémon in the event. There are so many Pokémon YouTubers who create news content there is no shortage of event raid information by Googling under this naming convention.

I will use your Krabby as an example. You will NEVER find reference to that specific Raid by searching Google. There's too many Mystery Gifts and Pokémon Go websites out there to narrow it down.

I argue the date naming convention is far more intuitive by the sheer volume of searchable content under the date-based naming convention.

Furthermore, there will be repeats in Pokémon returning to Raids. It's only a matter of time before Snorlax GMax and Toxtricity GMax return. What if the next Snorlax GMax is Lv. 60 instead of Lv. 70 and as such easier to capture? What is your plan to deal with duplicates because I believe you ALREADY have one!! Isn't Krabby the Toxtricity event??

**Comment by Admiral-Fish** [comment]
Because he was probably the first website to label them. Being the first to label something does not equal good naming conventions. He used some arbitrary naming convention for dens until a proper order from the game was documented(what Leanny and I use).

`The internet as a whole refers to Promoted Raids by Date with Year or Event`

I highly doubt this. Additionally year/date provide me no context about a raid without looking something up. The idea was to provide some context about the den without needing additional resources.

`You will NEVER find reference to that specific Raid by searching Google`

You clearly never looked up my repo on github.

`What is your plan to deal with duplicates`

As far as I am aware each new promotion has introduced at least one new pokemon which has been the basis of my convention.

But like I stated before, none of this conversation matters when any change to the naming would be a breaking change to RaidFinder. This is typically something I would prefer to avoid if at all possible.

**Comment by Th3Alic3** [comment]
> You clearly never looked up my repo on github.

You are correct. I like the vast majority of humans can barely navigate GitHub. I have this page bookmarked in Google.

> As far as I am aware each new promotion has introduced at least one new pokemon which has been the basis of my convention.

Krabby AND Toxtricity ARE the same event!
You already have duplicate events under the two different Pokémon due to your naming system.

Furthermore, you are assuming that EVERY single event data will add something new.

**Comment by Admiral-Fish** [comment]
Thank you for containing to ignore the most important point. It will stay as is for the foreseeable future so I don't break older versions of the program more then I have to.

**Comment by Admiral-Fish** [comment]
970290d is the best I can do for now

**Comment by Th3Alic3** [comment]
Without explanation as that I am no coder, I have no reference of context for the updates you made to the code nor will I see the difference until the next build.



If you are going to prioritize support for older versions of the software, that's your prerogative. I come from this only as a user. When an application with online functionality stops working for me, I do not stop using it. I simply download the newest version. The way I see this - it will just force people to the newer versions.

If you are worried people might look for an alternate app, you could future proof the application by adding some kind of a pop-up message when app thinks the Event Download looks different. Something like: _"You appear to be using an older version of Raid Finder. Please visit: https://github.com/Admiral-Fish/RaidFinder/ to update."_
