### ISSUE TITLE
Python Script.

### ISSUE THREAD

**Issue by xCayde-6** [Admiral-Fish/RaidFinder#6]
Everytime I try to open the Py script nfrom the main directory it instantly closes.  I then ran it through IDLE as a Python Shell, input the code from the raid_solver.py file. It then gives me Syntax Errors. I somehow managed to get it to work once and it gave me the "Main False" error and since then I get SyntaxErrors.
 I'm really new to this so any help is appreciated. Is there also any way of contacting you personally to make things go smoother if you're able to help out further. Thanks

**Comment by Admiral-Fish** [comment]
Are you using python 3.7?

Join the [pokemonrng discord](https://www.discord.gg/d8JuAvg) if you want a faster method of communication.
