### ISSUE TITLE
The game version setting in the configuration is useless

### ISSUE THREAD

**Issue by qhq** [Admiral-Fish/RaidFinder#61]
I set the shield in the Profile, but it is still the sword by default.
![QQ截图20200312113004](https://user-images.githubusercontent.com/3319385/76484606-34429d00-6455-11ea-95fd-f565321af831.png)

**Comment by Admiral-Fish** [comment]
The other windows don't have knowledge of the profiles. What behavior would you like to see?

**Comment by qhq** [comment]
My idea is that since the configuration file is set, all the places where the game version option is turned on default to the currently configured version. ：）
