### ISSUE TITLE
[Suggestion] Obtaining raid seed through trade screen

### ISSUE THREAD

**Issue by olliz0r** [Admiral-Fish/RaidFinder#7]
1. Raid host catches raid pokemon
2. Raid host does not save, initiates trade with a cfw'd player
3. Raid host shows the pokemon on the trade screen
4. CFW player dumps the pokemon from RAM (the full ek8 is in RAM at that time)
5. CFW player uses raid_solver.py to get the seed

The game doesn't save until the trade is concluded, so the Raid host can reset the game without losing the den/seed. 
Only thing needed for this would be the CFW player having a sysmodule to dump the pokemon at HEAP+0xAC843F68 and send it via wifi to the pc. This method would take a lot of load from the cfw'd player, as they don't have to take part in the raids anymore.

**Comment by zaksabeast** [comment]
This tools has been in the works - I'm hoping to release it in the next day or two.  @wwwwwwzx had the same idea with trades since initiating the trade doesn't save.

**Comment by Admiral-Fish** [comment]
https://github.com/zaksabeast/CaptureSight
