### ISSUE TITLE
Buttons dont work on 2.4.0 on Mojave (QDarkStyle)

### ISSUE THREAD

**Issue by Tithonius** [Admiral-Fish/RaidFinder#71]
All of the buttons, the Generate button, the Manage button for the profiles and other buttons don't do anything/work. The drop downs work, but i'm unable to use the buttons to do anything. They worked before the update to 2.4.0

**Comment by Admiral-Fish** [comment]
Seems to be an issue with the stylesheet. https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/235

Are you able to switch the style to "Light"?

**Comment by Tithonius** [comment]
That does fix the issue, yeah!

**Comment by Admiral-Fish** [comment]
I've reverted the version of QDarkStyle back to 2.8 from 2.8.1

**Comment by eAyangjian** [comment]
@Admiral-Fish 
Mac Mojave 10.14.6 still can't click Buttons to update event data
I have tested release 2.4.0 and 2.4.1

**Comment by mike-rosado** [comment]
Hi I've got Mac OS Catalina and the same is happening to me, I can click on any button, I can not even switch the style to light, any help?

Thanks

**Comment by Admiral-Fish** [comment]
Fixed by fa3fafa
