### ISSUE TITLE
Please teach me how to compile this source code on windows

### ISSUE THREAD

**Issue by KKMAA** [Admiral-Fish/RaidFinder#78]
I already download Visual Studio but I don't underderstand how to use......
I want to translate new map name to chinese

**Comment by Ich73** [comment]
RaidFinder is a Qt project. So it's best to install and use [Qt Creator](https://www.qt.io/offline-installers). Visit the page, select the tab `Qt Creator` and download the program for your operating system, e.g. [`Qt Creator 4.13.2 for Windows 64-bit (283 MB)`](https://download.qt.io/official_releases/qtcreator/4.13/4.13.2/qt-creator-opensource-windows-x86_64-4.13.2.exe).

Once you have it installed, you can download / fork and pull the repository and open `RaidFinder.pro` which is the project file using Qt Creator. You may need to tinker with the options in the `Tools > Options...` menu.

To get RaidFinder running you need to configure Build Settings. To do this select the `Projects` Tab on the left and add a new build configuration. I use a `Release` build configuration and `C:\pathToRaidFinder\build-release` as the build directory. To run it simply click the green arrow on the bottom left.

The files for translations can be found by selecting the `Edit` tab on the left and navigating to `RaidFinder [master] > Sources > i18n`. There are `RaidFinder_xx.ts` files you can edit. The tags `<translation type="unfinished"></translation>` need to be filled out with the proper translation. The abilities, characteristics, locations, natures and species can be found in `RaidFinder [master] > Resources > resources.qrc > /text`. After editing the files simply click the green arrow again to run RaidFinder and review your changes.

**Comment by Admiral-Fish** [comment]
To add on, you can also use [Qt Linguist](https://doc.qt.io/qt-5/qtlinguist-index.html) to have a dedicated tool for editing the `RaidFinder_xx.ts` files.

The other translation files in `Resources/Text` you only need a text editor.

**Comment by KKMAA** [comment]
> RaidFinder is a Qt project. So it's best to install and use [Qt Creator](https://www.qt.io/offline-installers). Visit the page, select the tab `Qt Creator` and download the program for your operating system, e.g. [`Qt Creator 4.13.2 for Windows 64-bit (283 MB)`](https://download.qt.io/official_releases/qtcreator/4.13/4.13.2/qt-creator-opensource-windows-x86_64-4.13.2.exe).
> 
> Once you have it installed, you can download / fork and pull the repository and open `RaidFinder.pro` which is the project file using Qt Creator. You may need to tinker with the options in the `Tools > Options...` menu.
> 
> To get RaidFinder running you need to configure Build Settings. To do this select the `Projects` Tab on the left and add a new build configuration. I use a `Release` build configuration and `C:\pathToRaidFinder\build-release` as the build directory. To run it simply click the green arrow on the bottom left.
> 
> The files for translations can be found by selecting the `Edit` tab on the left and navigating to `RaidFinder [master] > Sources > i18n`. There are `RaidFinder_xx.ts` files you can edit. The tags `<translation type="unfinished"></translation>` need to be filled out with the proper translation. The abilities, characteristics, locations, natures and species can be found in `RaidFinder [master] > Resources > resources.qrc > /text`. After editing the files simply click the green arrow again to run RaidFinder and review your changes.

compile error

https://i.imgur.com/QeEzJB5.png

**Comment by Ich73** [comment]
That's Visual Studio, not Qt Creator. And everything is chinese.
I'm willing to help, but what do you expect me/us to do with this information?

**Comment by YZYZYZGOD** [comment]
> 那是Visual Studio，而不是Qt Creator。一切都是中国人。
> 我愿意提供帮助，但是您希望我/我们如何处理这些信息？

I try to use QT creator compile raidfinder, but it seems something wrong, I wanna know which version QT Kits u chose

**Comment by YZYZYZGOD** [comment]
> > 那是Visual Studio，而不是Qt Creator。一切都是中国人。
> > 我愿意提供帮助，但是您希望我/我们如何处理这些信息？
> 
> I try to use QT creator compile raidfinder, but it seems something wrong, I wanna know which version QT Kits u chose

https://imgur.com/a/tUl6CjU
This is wrong message, it happend in Raid.cpp

**Comment by Ich73** [comment]
I'm running `Qt Creator 4.11.0 (Community)`. I also installed the C compilers using [Cygwin](https://cygwin.com/install.html).

In `Tools > Options... > Kits` in the Tab `Kits` I clicked `Add` to add a Manual Kit with the following settings:
  * Compiler C: MinGW (C, x86 64bit in C:\Program Files\Cygwin\bin)
  * Compiler C++: MinGW (C++, x86 64bit in C:\Program Files\Cygwin\bin)
  * Debugger: GDB in C:\Program Files\Cygwin\bin\gdb.exe
  * CMake Configuration:
```
CMAKE_CXX_COMPILER:STRING=%{Compiler:Executable:Cxx}
CMAKE_C_COMPILER:STRING=%{Compiler:Executable:C}
CMAKE_PREFIX_PATH:STRING=%{Qt:QT_INSTALL_PREFIX}
QT_QMAKE_EXECUTABLE:STRING=%{Qt:qmakeExecutable}
```

**Comment by YZYZYZGOD** [comment]
> I'm running `Qt Creator 4.11.0 (Community)`. I also installed the C compilers using [Cygwin](https://cygwin.com/install.html).
> 
> In `Tools > Options... > Kits` in the Tab `Kits` I clicked `Add` to add a Manual Kit with the following settings:
> 
> * Compiler C: MinGW (C, x86 64bit in C:\Program Files\Cygwin\bin)
> * Compiler C++: MinGW (C++, x86 64bit in C:\Program Files\Cygwin\bin)
> * Debugger: GDB in C:\Program Files\Cygwin\bin\gdb.exe
> * CMake Configuration:
> 
> ```
> CMAKE_CXX_COMPILER:STRING=%{Compiler:Executable:Cxx}
> CMAKE_C_COMPILER:STRING=%{Compiler:Executable:C}
> CMAKE_PREFIX_PATH:STRING=%{Qt:QT_INSTALL_PREFIX}
> QT_QMAKE_EXECUTABLE:STRING=%{Qt:qmakeExecutable}
> ```

thanks,I will try to use same compilers to compile it
