### ISSUE TITLE
Map Name translate to chinese

### ISSUE THREAD

**Issue by KKMAA** [Admiral-Fish/RaidFinder#79]
locations_zh.txt (Simplified Chinese)
牙牙湖之眼
桥间空地
沐光森林
沙尘洼地
牙牙湖东岸
巨人帽岩
巨人镜池
巨人凳岩
拳关丘陵
逆鳞湖
机擎河岸
美纳斯湖北岸
煦丽草原
美纳斯湖南岸
巨石原野
瞭望塔旧址
牙牙湖西岸
揖礼原野
清凉湿原
专注森林
挑战海滩
战斗洞窟
挑战之路
斗志洞窟
圆环海湾
锻炼平原
锅底沙漠
健身之海
列岛海域
离岛海域
蜂巢海
蜂巢岛
起橇雪原
冰点雪原
巨人睡榻
远古墓地
雪中​​溪谷
通顶雪道
王冠神殿
巨人鞋底
冻海
三岔平原
球湖湖畔
巨树丘陵

locations_tw.txt (Traditional Chinese)
牙牙湖之眼
橋間空地
沐光森林
沙塵窪地
牙牙湖東岸
巨人帽岩
巨人鏡池
巨人凳岩
拳關丘陵
逆鱗湖
機擎河岸
美納斯湖北岸
煦麗草原
美納斯湖南岸
巨石原野
瞭望塔舊址
牙牙湖西岸
揖禮原野
清涼濕原
專注森林
挑戰海灘
戰鬥洞窟
挑戰之路
鬥志洞窟
圓環海灣
鍛鍊平原
鍋底沙漠
健身之海
列島海域
離島海域
蜂巢海
蜂巢島
起橇雪原
冰點雪原
巨人睡榻
遠古墓地
雪中溪谷
通頂雪道
王冠神殿
巨人鞋底
凍海
三岔平原
球湖湖畔
巨樹丘陵

**Comment by Admiral-Fish** [comment]
#80 and #81
