### ISSUE TITLE
How do I check Promoted raids?

### ISSUE THREAD

**Issue by Sirorangeness** [Admiral-Fish/RaidFinder#84]
I haven't used this program in a while but I remember there being a specific 'Event' tab in the raid dens. But that seems to be missing in the newest update. Is there another way to do this or will this be a feature in the upcoming update? Thank you.

**Comment by Ich73** [comment]
You have to download the event data first. This can be done by choosing `Tools > Download Event Data`. You can then select the event you want to download the data for and click `OK`. A restart of Raid Finder is required to apply the changes.
You can then select the `Event` Den and continue as you're used to.

**Comment by Admiral-Fish** [comment]
To add on, the `Event` den will show at the top of any location as long as you have an event downloaded.
