### ISSUE TITLE
Account Manager Doesn't Work Anymore (Windows)

### ISSUE THREAD

**Issue by WilliytheGamerDude** [Admiral-Fish/RaidFinder#92]
Title says all. Whenever I try to make a new account, the app doesn't save the information, and now it's just gonna default to Sword all the time. PLEASE FIX THIS!!!!!

EDIT: This version is V2.7.1, in case you were wondering.

**Comment by Admiral-Fish** [comment]
My bad I didn't see this. What path are you saving the profiles too and what is in the file if it exists.

**Comment by WilliytheGamerDude** [comment]
I dunno what that means. I'm just using the in-app profile tool, if that's what you mean. I have no idea how to make any accounts otherwise.

**Comment by WilliytheGamerDude** [comment]
NVM, figured it out. I didn't have a profiles.json before now. My mistake.
